/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;
import Controlador.*;
import java.awt.*;
import java.awt.event.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.*;
/**
 *
 * @author Alumno
 */
public class DisenarModuloView extends javax.swing.JFrame {

    private DisenarModuloController diseno;
    private FinalViewController lista;
    private CrearPedidoController pedilo;
    private MenuPrincipalController menu; 
    private int alturaModulo = 1;
    private int anchoModulo = 1;
    private int profundidadModulo;
    private float escalaX = 1;
    private float escalaY = 1;
    private int moduloX;
    private int moduloY;
    private boolean dibujarDivisorio = false;
    private boolean esDivisorioHorizontal = false;
    private Point puntoInicioDivisorio = null;
    private List<Point> divisoriosHorizontales = new ArrayList<>();
    private List<Point> divisoriosVerticales = new ArrayList<>();
    private List<Integer> posicionesDivisoriosHorizontales = new ArrayList<>(); // Declaración aquí
    private List<Integer> posicionesDivisoriosVerticales = new ArrayList<>(); 

    
    public DisenarModuloView() {
    initComponents();

    jButton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (jCheckBox1.isSelected()) {
                    dibujarDivisorio = true;
                    esDivisorioHorizontal = true;
                    puntoInicioDivisorio = null;
                    jPanel2.setCursor(new Cursor(Cursor.CROSSHAIR_CURSOR));
                } else {
                    JOptionPane.showMessageDialog(DisenarModuloView.this, "Debe seleccionar la opción 'Divisorios'.");
                }
            }
        });

    jButton2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (jCheckBox1.isSelected()) {
                    dibujarDivisorio = true;
                    esDivisorioHorizontal = false;
                    puntoInicioDivisorio = null;
                    jPanel2.setCursor(new Cursor(Cursor.CROSSHAIR_CURSOR));
                } else {
                    JOptionPane.showMessageDialog(DisenarModuloView.this, "Debe seleccionar la opción 'Divisorios'.");
                }
            }
        });

jPanel2.addMouseListener(new MouseAdapter() {
    @Override
    public void mouseClicked(MouseEvent e) {
        if (dibujarDivisorio && puntoInicioDivisorio == null) {
            // Primer clic: marca el inicio del divisorio temporal
            puntoInicioDivisorio = e.getPoint();
            dibujarModuloConDivisorio(alturaModulo, anchoModulo, profundidadModulo);
            jPanel2.setCursor(new Cursor(Cursor.CROSSHAIR_CURSOR)); // Mantener el cursor de dibujo
        } else if (dibujarDivisorio && puntoInicioDivisorio != null) {
            // Segundo clic: fija la posición del divisorio
            jPanel2.setCursor(Cursor.getDefaultCursor());
            dibujarDivisorio = false;

            if (esDivisorioHorizontal) {
                int yFinal = puntoInicioDivisorio.y - moduloY;
                divisoriosHorizontales.add(new Point(0, yFinal));
                System.out.println("Divisorio Horizontal fijo en Y = " + yFinal + " píxeles relativos.");
            } else {
                int xFinal = puntoInicioDivisorio.x - moduloX;
                int yFinal = puntoInicioDivisorio.y - moduloY; // Guardar la coordenada Y también
                divisoriosVerticales.add(new Point(xFinal, yFinal));
                System.out.println("Divisorio Vertical fijo en X = " + xFinal + ", Y = " + yFinal + " píxeles relativos.");
            }

            esDivisorioHorizontal = false;
            puntoInicioDivisorio = null;
            dibujarModuloConDivisorio(alturaModulo, anchoModulo, profundidadModulo); // Redibujar con el divisorio fijo
        }
    }

    @Override
    public void mouseMoved(MouseEvent e) {
        if (dibujarDivisorio && puntoInicioDivisorio != null) {
            // Mientras se mueve el mouse, actualiza la posición del divisorio temporal
            puntoInicioDivisorio = e.getPoint();
            dibujarModuloConDivisorio(alturaModulo, anchoModulo, profundidadModulo);
        }
    }
});
    
 
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jCheckBox2 = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jCheckBox3 = new javax.swing.JCheckBox();
        jButton5 = new javax.swing.JButton();
        jCheckBox4 = new javax.swing.JCheckBox();
        jButton6 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setForeground(new java.awt.Color(0, 51, 102));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingrese Medidas");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Altura");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ancho");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Profundidad");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("mm");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("mm");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("mm");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Opciones");

        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Divisorios");

        jButton1.setText("Añadir Divisorio Horizontal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Añadir Divisorio Vertical");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jCheckBox2.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setText("Banquinas");

        jButton3.setText("Añadir Banquina Horizontal");

        jButton4.setText("Añadir Banquina Vertical");

        jCheckBox3.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox3.setText("Puertas");

        jButton5.setText("Seleccionar Ubicacion");

        jCheckBox4.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox4.setText("Cajones");

        jButton6.setText("Seleccionar Ubicacion");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Cantidad:");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Total:");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Total:");

        jButton7.setBackground(new java.awt.Color(153, 0, 0));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Salir");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Terminar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 527, Short.MAX_VALUE)
        );

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Vista Previa Modulo");

        jButton9.setText("Aceptar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel7))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel6))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel5))
                        .addComponent(jCheckBox1)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox2)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBox4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBox3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11))
                    .addComponent(jButton9))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(203, 203, 203))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox3)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jCheckBox4))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarDimensiones(int altura, int ancho, int profundidad) throws NumberFormatException {
    alturaModulo = Integer.parseInt(jTextField1.getText());
    anchoModulo = Integer.parseInt(jTextField2.getText());
    profundidadModulo = Integer.parseInt(jTextField3.getText());
}
    

    private void mostrarErrorMedidas() {
    JOptionPane.showMessageDialog(this, "Ingrese medidas válidas para el módulo (Altura, Ancho, Profundidad).", "Error", JOptionPane.ERROR_MESSAGE);
}

private void dibujarModulo(int alto, int ancho, int profundidad) {
    try {
        actualizarDimensiones(alto,ancho,profundidad);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Por favor ingrese valores numéricos válidos.");
        return;
    }

    if (alto <= 0 || alto > 2600 || ancho <= 0 || ancho > 1830) {
        JOptionPane.showMessageDialog(this, "Las dimensiones superan los límites permitidos.\nAltura máxima: 2600 mm\nAncho máximo: 1830 mm");
        return;
    }

    Graphics2D g2d = (Graphics2D) jPanel2.getGraphics(); // Obtener Graphics2D para configurar el grosor de la línea
    if (g2d == null) {
        return; // Salir si Graphics2D no está disponible
    }
    g2d.clearRect(0, 0, jPanel2.getWidth(), jPanel2.getHeight());

    // Cálculo de escalado para ajustar el módulo al tamaño del panel
    float escalaX = (float) jPanel2.getWidth() / 1830;
    float escalaY = (float) jPanel2.getHeight() / 2600;

    int anchoDibujado = Math.round(ancho * escalaX);
    int altoDibujado = Math.round(alto * escalaY);

    // Centrado en el panel
    int x = (jPanel2.getWidth() - anchoDibujado) / 2;
    int y = (jPanel2.getHeight() - altoDibujado) / 2;

    g2d.setColor(Color.BLACK);
    g2d.setStroke(new BasicStroke(5)); // Establecer el grosor de la línea a 3 (puedes ajustar este valor)
    g2d.drawRect(x, y, anchoDibujado, altoDibujado);

    g2d.dispose();
}

 private void dibujarModuloConDivisorio(int alto, int ancho, int profundidad) {
    Graphics2D g2d = (Graphics2D) jPanel2.getGraphics();
    if (g2d == null) {
        return;
    }
    g2d.clearRect(0, 0, jPanel2.getWidth(), jPanel2.getHeight());
    g2d.setColor(Color.BLACK);
    g2d.setStroke(new BasicStroke(5));

    escalaX = (float) jPanel2.getWidth() / 1830;
    escalaY = (float) jPanel2.getHeight() / 2600;

    int anchoDibujado = Math.round(ancho * escalaX);
    int altoDibujado = Math.round(alto * escalaY);

    moduloX = (jPanel2.getWidth() - anchoDibujado) / 2;
    moduloY = (jPanel2.getHeight() - altoDibujado) / 2;

    g2d.drawRect(moduloX, moduloY, anchoDibujado, altoDibujado);

    g2d.setColor(Color.BLACK);
    g2d.setStroke(new BasicStroke(3));

    for (Point ph : divisoriosHorizontales) {
        int yDivisorio = moduloY + ph.y;
        g2d.drawLine(moduloX, yDivisorio, moduloX + anchoDibujado, yDivisorio);
    }

    for (Point pv : divisoriosVerticales) {
        int xDivisorio = moduloX + pv.x;
        int yInicio = moduloY + pv.y; // Usar la coordenada Y guardada como punto de inicio
        int yFin = moduloY + altoDibujado;

        // Ajustar el fin de la línea vertical según los divisores horizontales que estén POR DEBAJO del inicio
        for (Point ph : divisoriosHorizontales) {
            int yDiv = moduloY + ph.y;
            if (yDiv > yInicio && yDiv < yFin) {
                yFin = Math.min(yFin, yDiv);
            }
        }
        // Ajustar el inicio de la línea vertical según los divisores horizontales que estén POR ENCIMA del inicio
        int moduloSuperior = moduloY;
        for (Point ph : divisoriosHorizontales) {
            int yDiv = moduloY + ph.y;
            if (yDiv < yInicio && yDiv > moduloSuperior) {
                moduloSuperior = Math.max(moduloSuperior, yDiv);
                yInicio = moduloSuperior;
            }
        }
        g2d.drawLine(xDivisorio, yInicio, xDivisorio, yFin);
    }

    if (dibujarDivisorio && puntoInicioDivisorio != null) {
        g2d.setColor(Color.RED);
        g2d.setStroke(new BasicStroke(2));
        if (esDivisorioHorizontal) {
            g2d.drawLine(moduloX, puntoInicioDivisorio.y, moduloX + anchoDibujado, puntoInicioDivisorio.y);
        } else {
            int xTemp = puntoInicioDivisorio.x;
            int yTemp = puntoInicioDivisorio.y;
            int yInicioTemp = moduloY;
            int yFinTemp = moduloY + altoDibujado;
            for (Point ph : divisoriosHorizontales) {
                int yDiv = moduloY + ph.y;
                if (yDiv > yTemp && yDiv < yFinTemp) {
                    yFinTemp = Math.min(yFinTemp, yDiv);
                }
                if (yDiv < yTemp && yDiv > yInicioTemp) {
                    yInicioTemp = Math.max(yInicioTemp, yDiv);
                }
            }
            g2d.drawLine(xTemp, yInicioTemp, xTemp, yFinTemp);
        }
    }

    g2d.dispose();
}
    
    
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        diseno.ocultar();
        pedilo.mostrar();
        menu.mostrar();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        diseno.ocultar();
        lista.mostrar();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        actualizarDimensiones(alturaModulo, anchoModulo, profundidadModulo);
        dibujarModulo(alturaModulo,anchoModulo,profundidadModulo);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dibujarModuloConDivisorio(alturaModulo,anchoModulo,profundidadModulo);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dibujarModuloConDivisorio(alturaModulo,anchoModulo,profundidadModulo);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisenarModuloView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisenarModuloView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisenarModuloView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisenarModuloView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisenarModuloView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

    public JTextField getjTextField1() {
        return jTextField1;
    }

    public void setjTextField1(JTextField jTextField1) {
        this.jTextField1 = jTextField1;
    }

    public JTextField getjTextField2() {
        return jTextField2;
    }

    public void setjTextField2(JTextField jTextField2) {
        this.jTextField2 = jTextField2;
    }

    public JTextField getjTextField3() {
        return jTextField3;
    }

    public void setjTextField3(JTextField jTextField3) {
        this.jTextField3 = jTextField3;
    }

}
