/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;
import javax.swing.*;
import java.util.*;
import Controlador.*;

public class FinalView extends javax.swing.JFrame {

    private int idPedido;
    private int cantidadModulos;

    public FinalView(int idPedido, int cantidadModulos) {
        this.idPedido = idPedido;
        this.cantidadModulos = cantidadModulos;
        initComponents();
        FinalViewController controlador = new FinalViewController();
        List<Map<String, List<double[]>>> listaDespiece = controlador.obtenerListaDespiece(idPedido);
        mostrarDespieceEnTabla(cantidadModulos, listaDespiece);
    }

    // Constructor vacío solo para pruebas o para el ma

    public FinalView() {
        //TODO Auto-generated constructor stub
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setForeground(new java.awt.Color(0, 51, 102));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Resultados Despiece");

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Zocalo", null, null, null, null, null},
                {"Cabezal", null, null, null, null, null},
                {"Laterales", null, null, null, null, null},
                {"Div Horizontal", null, null, null, null, null},
                {"Div Vertical", null, null, null, null, null},
                {"Banq Horizontal", null, null, null, null, null},
                {"Banq Vertical", null, null, null, null, null},
                {"Base Cajon", null, null, null, null, null},
                {"Frente Cajon", null, null, null, null, null},
                {"Lateral Cajon", null, null, null, null, null},
                {"Tapa Cajon", null, null, null, null, null},
                {"Puertas", null, null, null, null, null}
            },
            new String [] {
                "Cortes", "Modulo 1", "Modulo 2", "Modulo 3", "Modulo 4", "Modulo 5"
            }
        ));
        jTable1.setRowHeight(30);
        jScrollPane1.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(153, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Guardar");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Precio Aproximado:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cantidad de Placas necesarias:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 851, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Llena el jTable1 con los resultados del despiece de cada módulo.
     * @param cantidadModulos cantidad de módulos diseñados
     * @param listaDespiece lista de mapas, uno por módulo, con clave el nombre del componente y valor una lista de arreglos [ancho, largo, cantidad]
     */
    public void mostrarDespieceEnTabla(int cantidadModulos, List<Map<String, List<double[]>>> listaDespiece) {
        if (listaDespiece == null || listaDespiece.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No hay datos de despiece para mostrar.");
        return;
        } 
        String[] nombresComponentes = {
            "Zocalo", "Cabezal", "Laterales", "Div Horizontal", "Div Vertical",
            "Banq Horizontal", "Banq Vertical", "Base Cajon", "Frente Cajon",
            "Lateral Cajon", "Tapa Cajon", "Puertas"
        };

        // Construir columnas dinámicamente
        String[] columnas = new String[cantidadModulos + 1];
        columnas[0] = "Cortes";
        for (int i = 1; i <= cantidadModulos; i++) {
            columnas[i] = "Modulo " + i;
        }

        Object[][] datos = new Object[nombresComponentes.length][cantidadModulos + 1];
        for (int i = 0; i < nombresComponentes.length; i++) {
            datos[i][0] = nombresComponentes[i];
            for (int j = 0; j < cantidadModulos; j++) {
                Map<String, List<double[]>> despieceModulo = listaDespiece.get(j);
                List<double[]> lista = despieceModulo.getOrDefault(nombresComponentes[i], new ArrayList<>());
                if (lista.isEmpty()) {
                    datos[i][j + 1] = "-";
                } else {
                    // Si hay varios componentes iguales, los listamos separados por coma
                    StringBuilder sb = new StringBuilder();
                    for (double[] pieza : lista) {
                        int ancho = (int) Math.round(pieza[0]);
                        int largo = (int) Math.round(pieza[1]);
                        int cantidad = pieza.length > 2 ? (int) Math.round(pieza[2]) : 1;
                        sb.append(ancho).append("x").append(largo).append(" (").append(cantidad).append("), ");
                    }
                    // Quitar la última coma y espacio
                    if (sb.length() > 2) sb.setLength(sb.length() - 2);
                    datos[i][j + 1] = sb.toString();
                }
            }
        }

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            datos,
            columnas
        ));
        jTable1.setRowHeight(30);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
